#checking helmfile
helmfiles:
  - path: ./charts/backbone-services/backboneservices-helmfile.yaml
  - path: ./charts/core-services/coreservices-helmfile.yaml
  - path: ./charts/monitoring/monitoring-helmfile.yaml
  - path: ./charts/business-services/businessservices-helmfile.yaml
  - path: ./charts/frontend/frontend-helmfile.yaml

